### ISSUE TITLE
Link template 'edit-form' for entity type 'lti_tool_provider_consumer' must start with a leading slash

### ISSUE THREAD

**Issue by tstecca** [rmassoud/lti_tool_provider#1]
I'm getting a fatal error : Link template 'edit-form' for entity type 'lti_tool_provider_consumer' must start with a leading slash.  

I've edited the consumer.php file  to include these leading slashes on the links declaration.  It has cleared the critical error but now the status report is staying "The Consumer entity entity type needs to be installed."

**Comment by rmassoud** [comment]
Looks like Drupal8 has changed a lot from the beta release which I used to develop this module. I've fixed this issue for now but I'm expecting more issues to be fixed.

**Comment by tstecca** [comment]
This issue has been fixed by rmassoud in his latest patch.  Cheers rmassoud.  Marking as closed.
